### ISSUE TITLE
Keep annotations on CGLIB proxies

### ISSUE THREAD

**Issue by maffeis** [cglib/cglib#105]
It would be nice if the generated CGLIB proxy could somehow inherit the annotations which are present on the proxied parent class, even if the annotation itself is not marked with @Inherited

**Comment by raphw** [comment]
cglib does not offer this feature and it is unlikely that this will be added to cglib which was created long before annotations were added to Java.

You can do this by using [Byte Buddy](http://bytebuddy.net) if you require such functionality.
