### ISSUE TITLE
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (jdk9)

### ISSUE THREAD

**Issue by J-cztery** [cglib/cglib#129]
Hello, 
I was wondering if this is something that you are planning on fixing the illegal reflective access warnings?
The following is the snippet from the java (9.0.4) run with --illegal-access=debug

WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file: /lib/cglib-nodep-3.2.7.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
	at net.sf.cglib.core.ReflectUtils$1.run(ReflectUtils.java:61)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.sf.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:52)
	at net.sf.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:243)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:157)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:149)

**Comment by raphw** [comment]
This would require a major API change. cglib is no longer under active development and considering the many changes in the JVM laying ahead, this library will no longer support future JVMs unless some major work is put into it.

I would therefore recommend you to migrate to another code generation library such as Javassist or Byte Buddy which do already support the newer JVMs.

**Comment by J-cztery** [comment]
Thanks @raphw . Will do.

**Comment by aaime** [comment]
@raphw I see you say that "cglib is no longer under active development" and yet after Aug 3 I see commits and even a release. Did something change or what I'm seeing is just "life support"?

**Comment by raphw** [comment]
There is still some general maintenance but there will no longer be any features, unless someone wants to pick up the library. Over time, I argue that you are better off with an alternative, if you want to support modules, for example.

**Comment by aaime** [comment]
Thanks for the confirmation. I had a quick look at ByteBuddy, which seems to be supported, but cannot just dump a 3Mb (10 times larger) library in the classpath just like that. Is there any other alternative? 
I've also started a question on stackoverflow on the particular issue that I'm trying to solve, so far, without answer: https://stackoverflow.com/questions/52990579/lazy-loader-alternative-to-cglib

**Comment by sameb** [comment]
@raphw, out of curiosity, how massive an undertaking do you think it'd be to support modules in cglib?

**Comment by raphw** [comment]
It is not really possible if you want to retain the general approach. Proxies are injected in target modules where any dynamic class has a cglib dependeny via the proxy dispatcher types. Any proxy classes' module must therefore read the module of cglib what therefore requires adjusting the module graph if not any module that contains proxied classes explicitly reads cglib in its module-info.

You could of course add a static initializer to any generated proxy that adds the read (new edges must be created by the reading module) but this would effectively disable the module system at runtime.

Spring circumvents this by shading cglib what reduces the impact but any Spring bean must still read Spring Core if modules are used.

Byte Buddy weaves byte code directly into injected classes without any dispatchers to circumvent this problem.

**Comment by raphw** [comment]
Let's say that you are using library A and you want to declare an instance of a class of A as a Spring bean. Library A is modularized and does not know anything about Spring or cglib. But to work, it would need to.

**Comment by sameb** [comment]
Thanks. A few more questions:

   - Can a package have more than one module?  If so, could we create the dynamic class in a new module?  Or would doing that break anyway because the old module (with the original class) wouldn't be exposed to the new module?

  - IIUC, ByteBuddy still generates new classes, but the new classes don't contain any references to ByteBuddy itself.  Presumably cglib could do the same, but it'd just be a fairy massive change to how cglib works?

  - You mention the module stuff can be manually manipulated to add cglib to its deps, at the cost of effectively disabling the module runtime.  Is it actually disabling it, or just hijacking it to manually add cglib in a way that the original library might not have intended?  If we did this, would other aspects of the module system continue to work (e.g, preventing other modules from using the manipulated one if they were listed in it)?
