### ISSUE TITLE
BeanCopier.java problem

### ISSUE THREAD

**Issue by yseasony** [cglib/cglib#29]
line 112 
PropertyDescriptor[] setters = ReflectUtils.getBeanGetters(target);

whether should be modified to

PropertyDescriptor[] setters = ReflectUtils.getBeanSetters(target);

**Comment by raphw** [comment]
Thanks for reporting this. By the way, you are always welcome to add a pull request!

**Comment by raphw** [comment]
This is fixed and can be closed.
