### ISSUE TITLE
Change of code history

### ISSUE THREAD

**Issue by raphw** [cglib/cglib#31]
Hi,

I committed my last updates with a fresh work machine and my git config was not properly set up. I would ask you to please remove this data from the commit history as it contains some (now changed) workgroup codes from my work place which I would prefer to not have online. Really no idea how they ended up there, I might have copy-pasted something without noticing at some point.

You can do the changes as follows from the current state:

```java
git rebase -i -p HEAD~2
(press insert in VIM, change puth lines to begin with 'e', escape, type ':wq' to save and close)
git commit --amend --author "Rafael Winterhalter <rafael.wth@web.de>" 
(in VIM, press esape, type ':wq')
git rebase --continue
git commit --amend --author "Rafael Winterhalter <rafael.wth@web.de>" 
(in VIM, press esape, type ':wq')
git rebase --continue
git push --force
```

Thank you and sorry for the extra work, I should know git better than that.

**Comment by sameb** [comment]
Done, no worries.  Thanks for the detailed instructions. :-)

**Comment by raphw** [comment]
Thanks a lot!
