### ISSUE TITLE
Please release 3.2

### ISSUE THREAD

**Issue by EdGrahamJr** [cglib/cglib#32]
We could really use the Java 8 "release"...

**Comment by pniederw** [comment]
+10000. This causes incredible pain for downstream libraries and their users.

**Comment by pniederw** [comment]
Finally found a workaround for Maven/Gradle builds that need latest CGLIB: Add Maven repository `https://jitpack.io` and dependency `com.github.cglib:cglib.cglib-nodep:e10bc3dda2`. This will dynamically build the latest sources (commit e10bc3dda2) and make them available as a Maven dependency.

**Comment by raphw** [comment]
I think the cglib release still depends on validating the Java 8 properties. I will try to find some time to look at this at some point. However, any help is appreciated if someone else feels like contributing!

**Comment by EdGrahamJr** [comment]
Duplicate of #20

**Comment by ilCatania** [comment]
(in response to pniederw's workaround) The submodule syntax on jitpack.io appears to have changed, in order to include a `cglib-nodep` snapshot you need to use this dependency string instead: `com.github.cglib.cglib:cglib-nodep:5503bcca74`
