### ISSUE TITLE
Switch to Opcodes.ASM5

### ISSUE THREAD

**Issue by HiJon89** [cglib/cglib#33]
It looks like CGLIB version 3.2 will upgrade ASM dep to 5.0.3, but `Opcodes.ASM4` is still being passed everywhere. Are there any plans to change this before 3.2 release? It causes runtime exceptions when trying to proxy classes compiled with the `-parameters` flag

**Comment by sameb** [comment]
There are no plans to make any changes unless people submit pull requests (preferably with tests & explanations).  cglib isn't actively maintained, sorry.

**Comment by HiJon89** [comment]
Ok I will work on that. It requires a Java 8 class file to reproduce, would you prefer I add a new module targeting 1.8 to generate the class file or add a precompiled Java 8 class file under src/test/resources?

**Comment by sameb** [comment]
New module'd be preferable, thanks!

**Comment by sameb** [comment]
Fixed in https://github.com/cglib/cglib/commit/6238d92d741c1d7a149962bfc204c060346ff334
