### ISSUE TITLE
can't deploy release because some maven output is missing

### ISSUE THREAD

**Issue by sameb** [cglib/cglib#46]
@JBodkin (or anyone else), can you help with some maven issues?  I tried deploying a new release this past week, but I can't promote from staging because when I try to close the staging output, it fails verification saying that some files are missing.  See https://issues.sonatype.org/browse/OSSRH-18447, or below:

```
Event: Failed: Javadoc Validation
Friday, October 23, 2015 15:34:26 EDT (GMT-0400)
typeId	javadoc-staging
failureMessage	Missing: no javadoc jar found in folder '/cglib/cglib-nodep/3.2.0'
Event: Failed: Signature Validation
Friday, October 23, 2015 15:34:36 EDT (GMT-0400)
typeId	signature-staging
failureMessage	Invalid Signature: '/cglib/cglib-sample/3.2.0/cglib-sample-3.2.0-site.jar.asc' is not a valid signature for 'cglib-sample-3.2.0-site.jar'.
failureMessage	Missing Signature: '/cglib/cglib-sample/3.2.0/cglib-sample-3.2.0.jar.asc' does not exist for 'cglib-sample-3.2.0.jar'.
failureMessage	Invalid Signature: '/cglib/cglib-sample/3.2.0/cglib-sample-3.2.0-javadoc.jar.asc' is not a valid signature for 'cglib-sample-3.2.0-javadoc.jar'.
failureMessage	Invalid Signature: '/cglib/cglib-sample/3.2.0/cglib-sample-3.2.0-sources.jar.asc' is not a valid signature for 'cglib-sample-3.2.0-sources.jar'.
failureMessage	Invalid Signature: '/cglib/cglib/3.2.0/cglib-3.2.0-javadoc.jar.asc' is not a valid signature for 'cglib-3.2.0-javadoc.jar'.
failureMessage	Missing Signature: '/cglib/cglib/3.2.0/cglib-3.2.0.jar.asc' does not exist for 'cglib-3.2.0.jar'.
failureMessage	Missing Signature: '/cglib/cglib-nodep/3.2.0/cglib-nodep-3.2.0.jar.asc' does not exist for 'cglib-nodep-3.2.0.jar'.
failureMessage	Missing Signature: '/cglib/cglib-integration-test/3.2.0/cglib-integration-test-3.2.0.jar.asc' does not exist for 'cglib-integration-test-3.2.0.jar'.
```

... I suspect the POM needs updating to produce those files?

**Comment by raphw** [comment]
As far asI remember was the Maven build copied from my setup for Byte Buddy: https://github.com/raphw/byte-buddy/blob/master/byte-buddy/pom.xml

A module without source will not produce a javadoc jar. It needs to be copied from the non-shaded module. Simply imitate what I did in my build and it should work. Maybe I can send a pull request sometime this week if no one else has time.

**Comment by raphw** [comment]
Also, your gdp key seems to be set up incorrectly.

**Comment by sameb** [comment]
The key is setup correctly, my command for deploying just happened to have gpg:sign before the jars were created, so it wasn't signing them.
