### ISSUE TITLE
Add more committers

### ISSUE THREAD

**Issue by sameb** [cglib/cglib#58]
I don't have the time to keep up with all the PRs for this project, so I'd like to add more committers.

Based on recent activity, the following folks may be interested:
   @JBodkin 
   @lukesandberg 
   @raphw 
   @guw  

If you'd like to be a committer, please respond on this issue.  I ask only that you 
   1) Ensure tests are added with new code and are meaningful (e.g, fail w/o the fixes, pass w/ them)
   2) Any new APIs are sane.  If you're unsure about sanity, just ask.
   3) Keep backwards compatibility as much as possible.

**Comment by raphw** [comment]
I am good with looking into pull requests every now and then. I maintain the Byte Buddy library so I have a good overview on the subject matter, so I hope it is not too much extra work.

**Comment by guw** [comment]
Thanks! I'm also good with providing pull requests when there is a need to contribute something.

**Comment by sameb** [comment]
@guw, does that mean you'd prefer I not add you as a committer?

**Comment by guw** [comment]
@sameb Yes, I'm happy with the contributor role.
