### ISSUE TITLE
Doesn't fail gracefully when kotlin method is not open 

### ISSUE THREAD

**Issue by jasperblues** [cglib/cglib#62]
**Steps to Repro:**

Create a cglib proxy of a Kotlin class. 
Proxy a closed method

Expected outcome: 

Fails warning that method is not open

Actual outcome: 

Does not fail, but method is also not proxied. In spring this means a test marked @Transactional won't roll back, etc. . .

**Comment by raphw** [comment]
A non-open method in Kotlin is compiled into a `final` method. Such methods are simply ignored by cglib, this is part of the contract of the `Enhancer`. It is your responsibility to not rely on such methods being overridden.

For example, `Object` already defines `final` methods such as `notify` what would make it impossible to create a proxy for any class.

**Comment by jasperblues** [comment]
Yes indeed. Though I haven't looked at the enhancer source, I thought perhaps CGLib could report a meaningful error if an attempt to proxy a final method is made. So if this behavior was required the responsibility would fall on the client _using_ cglib? (in this case spring).

**Comment by raphw** [comment]
Yes, this would be the case. Cglib filters all final methods. The problem here is that Kotlin sets methods and classes to be final by default while its an explicit act in Java. Cglib simply assumes that a final method was intended to be proxied.

**Comment by jasperblues** [comment]
OK, thank you for the explanation! 

Incidentally, there's a discussion here on whether closed-by-default should be the case in 1.0: https://discuss.kotlinlang.org/t/classes-final-by-default/166

 While there's some arguments in favor my preference for this _not_ to be the case. However, I think it would be unlikely to change so close to release now though, especially given that somewhat of a majority were pointing in the other direction, including the language authors.
