### ISSUE TITLE
Regression when using javax.tools.JavaCompiler

### ISSUE THREAD

**Issue by jqno** [cglib/cglib#64]
In CGLib 3.2.0 I was able to generate a subclass from a class that was compiled using `javax.tools.JavaCompiler`, but in 3.2.1 it's no longer possible. I've put a small project up on GitHub to reproduce it: https://github.com/jqno/cglib-javax-compiler-issue

The pom now points to CGLib 3.2.1 and the test fails, but if you change it to 3.2.0, the test passes.

Come to think of it, this issue is pretty ridiculous: combining 2 different ways of generating code... But it comes from a [real project](https://github.com/jqno/equalsverifier) :). This issue is not high priority for me, though. I'll stick with 3.2.0 for now.

**Comment by vlsi** [comment]
#66 fixes cglib-javax-compiler-issue issue for me

**Comment by vlsi** [comment]
@jqno , https://github.com/jqno/equalsverifier does not use cglib. How come you face cglib issue there?

**Comment by jqno** [comment]
I'm still using 3.1 on the dev_version_1x branch. A user reported an issue
that would be fixed if I switch to 3.2.0, but 3.2.1 introduces the issue
above.

**Comment by vlsi** [comment]
Do you think it makes sense to add a Travis job to use dev_version_1x as a cglib regression test?

**Comment by sameb** [comment]
sorry, what is dev_version_1x?

**Comment by jqno** [comment]
@vlsi Sure! There's already a Travis job there, just let me know what I can do to make things easier for you.

@sameb I've started development on version 2, but I still want to do bugfixes to version 1. So, master = 2.x and dev_version_1x = 1.x.

**Comment by vlsi** [comment]
@sameb , we are talking about  https://github.com/jqno/equalsverifier project's branches here.

@jqno, I was thinking of adding build "equalsverifier against snapshot cglib" at cglib side to catch regressions. I wonder if you can use a property to specify cglib version, so at cglib's Travis something like `git clone equalsverifier; mvn test -Dequalsverifier.cglib.version=...` would be used to build against current .

**Comment by jqno** [comment]
@vlsi Sounds good to me. I can update the build script to make that possible. Given that this issue is now closed, maybe it's a good idea if you open an issue on the EqualsVerifier issue tracker for this?

**Comment by vlsi** [comment]
@jqno , here you go: https://github.com/jqno/equalsverifier/pull/133/
