### ISSUE TITLE
3.2.2 Release request

### ISSUE THREAD

**Issue by elrodro83** [cglib/cglib#69]
I have run the spring build with the cglib master including the fixes https://github.com/cglib/cglib/pull/65 and https://github.com/cglib/cglib/pull/66 and it finished correctly, so it would be good to have a cglib version out that is fully compatible with 3.2.0 and can be used in spring 4.2.x.

Thanks!

**Comment by jhoeller** [comment]
Spring Framework 4.2.6 is scheduled for release on March 24th, along with 4.3 RC1. If CGLIB 3.2.2 is out by then, we'll certainly pick it up. Thanks for the upfront integrating testing!

**Comment by elrodro83** [comment]
@sameb Can you take a look please?

**Comment by sameb** [comment]
Yup, I'll take a look when I have some time.

**Comment by jhoeller** [comment]
A quick update: Our 4.2.6 is scheduled for March 30th now, that is, in a week's time. If CGLIB 3.2.2 is out by then, even just a day ahead, we'd pick it up still.

**Comment by sameb** [comment]
Sorry for the delay, been busy with work stuff.  I'll try to push the
release this week.

**Comment by jhoeller** [comment]
Another quick update from my side: For better or for worse, Spring Framework 4.2.6 isn't out yet; our target is Tuesday April 5th now. Positively speaking, still a chance to grab CGLIB 3.2.2 :-)

**Comment by francm** [comment]
I can confirm, that my memory leak issue is solved with latest cgilib/spring build. Thank you, i am looking forward for release.

**Comment by sameb** [comment]
released now, may take a bit for the release to show up on maven central.

sorry for the delay.

**Comment by vlsi** [comment]
Nice.
Thank you.

**Comment by elrodro83** [comment]
Thanks very much!

**Comment by jhoeller** [comment]
Thanks! Picked up for the upcoming Spring Framework 4.3 RC2 and also for our postponed 4.2.6...
