### ISSUE TITLE
Caching of FastClass does not work

### ISSUE THREAD

**Issue by kenwenzel** [cglib/cglib#91]
This issue was found by inspecting a memory leak in Google Guice:
https://github.com/google/guice/issues/1042

**These are my findings after digging into the problem:**
- FastClass.Generator is a sub class of AbstractClassGenerator
- AbstractClassGenerator supports caching of generated classes:
- https://github.com/cglib/cglib/blob/master/cglib/src/main/java/net/sf/cglib/core/AbstractClassGenerator.java#L116
- Maybe I am wrong but the primary lookup key for the generated classes is the FastClass.Generator instance itself
- FastClass.Generator does not implement hashCode() and equals()
- This effectively means that CGLIB always creates a new FastClass instead of using a cached one

**Proposed fix:**
- Implement  hashCode() and equals() for FastClass.Generator

**Comment by vlsi** [comment]
AFAIK, FastClass.Generator uses type name as a cache key: https://github.com/cglib/cglib/blob/28aa2484f1c4a85ac61eb11cb477040f217b7b0e/cglib/src/main/java/net/sf/cglib/reflect/FastClass.java#L65

**Comment by kenwenzel** [comment]
OK, I've overlooked that LoadingCache uses a helper for mapping of objects to concrete keys.
