### ISSUE TITLE
New release with Jigsaw-compatible class definition

### ISSUE THREAD

**Issue by raphw** [cglib/cglib#94]
On Jigsaw, it is no longer possible to reflect on protected methods of a foreign module and `ClassLoader::defineClass` is no longer accessible. Therefore, cglib now falls back onto Unsafe. Can you trigger a new release @sameb?

**Comment by jhoeller** [comment]
@raphw @sameb, indeed, it'd be great to have a 3.2.5 release including that patch.

There's also ASM 5.2 to pick up in the meantime, so worth upgrading that one for cglib-nodep as well.

**Comment by uschindler** [comment]
EasyMock is using cglib, too, so it would be great to get a release. They are prepared to trigger a release once cglib 3.2.5 is available. See #93 and https://github.com/easymock/easymock/issues/193

Currently we disabled all EasyMock-tests in Apache Solr when running with Java 9. In contrast Mockito works (as it uses ByteBuddy). We are planning to move all tests to Mockito, but that's a bit of work.

**Comment by nicolasbarbier** [comment]
Any idea when this release will happen? We are awaiting it anxiously :-).

**Comment by PascalSchumacher** [comment]
I new release would be very nice indeed.

AssertJ use cglib for its soft-assertions feature and with the current release this fails on java-9 build 157 with `java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer` (https://github.com/joel-costigliola/assertj-core/issues/927).

**Comment by raphw** [comment]
Ping @sameb

**Comment by PascalSchumacher** [comment]
@sameb A new release, pretty please?

**Comment by jhoeller** [comment]
What does it take to make this happen? If @sameb isn't reachable, can somebody else pick up the release procedure? With several stakeholders waiting for it, it'd be a shame to drag this out any longer...

**Comment by raphw** [comment]
I would do it if I had the credentials.

**Comment by sameb** [comment]
I'll try to get this done today. Sorry for being MIA.

**Comment by sameb** [comment]
Done.  Sorry for the delay.

**Comment by PascalSchumacher** [comment]
Thanks! :+1:

**Comment by jhoeller** [comment]
3.2.5 works fine in our Spring Framework integration tests. Thanks a lot, @sameb!
