### ISSUE TITLE
TinyBitSet: is it used/useful

### ISSUE THREAD

**Issue by ham1** [cglib/cglib#96]
I stumbled across the `TinyBitSet` and noticed a small improvement; I then added some more tests but wondered why it would be useful (as there isn't any documentation).

Some possible bugs:
1. set bits `0-31` then bits `32..` are already set
2. set bit `31` then `cardinality()` results in an infinite loop

After a bit of searching it doesn't seem that this code is used anywhere (in the open source world) apart from copies of it or its test file.

Can we delete it or document (and test and maybe fix it)?

**Comment by raphw** [comment]
This library is rather old and quite wide-spread. Removing existing classes is not really an option. But yes, with today's VMs, this is no longer useful. I would however argue that it is best to retain this (potentially buggy) behaviour as it might break dependants and no current users would build a new dependency.

**Comment by ham1** [comment]
Is it worth deprecating the class and documenting its shortcomings (with or without my modification to the code)?

**Comment by raphw** [comment]
Yes, absolutely, if you send a PR, I would merge that.

**Comment by ham1** [comment]
I've updated the PR.

I can re-add the test changes that demonstrate its flaws if that would also be useful?

**Comment by raphw** [comment]
Please do. Those don't hurt and serve as problem documentation. Ignore with an appropriate comment if they fail!

**Comment by ham1** [comment]
Done (as a separate commit, shall I squash into 1?)

**Comment by raphw** [comment]
No need, I squashed on merge. Thanks!
